import React, { useState } from "react";
import Navbar from "../components/Navbar";
import RightSidebar from "../components/RightSidebar";
import Sidebar from "../components/Sidebar";
import Head from "next/head";
import Swal from "sweetalert2";
import route from "next/router";
import RhService from "../services/RhService";

function AssignTasks() {
  const [data, setData] = useState({});
  const onChangeHandler = (e) => {
    setData({
      ...data,
      [e.target.name]: e.target.value,
    });
  };
  const onSubmitHandler = (e) => {
    e.preventDefault();
    const form = new FormData();
    form.append("sections", data.sections);
    form.append("enddate", data.enddate);
    form.append("Id", data.Id);
    form.append("RankId", data.RankId);
    form.append("Summary", data.Summary);

    Swal.fire({
      title: "Do you want to save the changes?",
      showDenyButton: true,
      showCancelButton: true,
      confirmButtonText: "Save",
      denyButtonText: "Don't save",
    }).then((result) => {
      /* Read more about isConfirmed, isDenied below */
      if (result.isConfirmed) {
        route.push("/Tasks");
        RhService.createTask(form)
          .then((res) => {
            console.log(res);
          })
          .catch((err) => {
            console.log(err);
          });
        Swal.fire("Saved!", "", "success");
      } else if (result.isDenied) {
        Swal.fire("Changes are not saved", "", "info");
      }
    });
  };
  return (
    <div className="flex">
      <Head>
        <title>PFE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://cdn.syncfusion.com/ej2/20.1.55/material.css"
          rel="stylesheet"
        ></link>
      </Head>

      <Sidebar />
      <div className=" bg-myColors-100 h-screen w-7/12 relative">
        <Navbar navBarTitle_1="Tasks" navBarTitle_2="Assign Tasks" />
        <div className="bg-myColors-200 rounded-2xl w-7/12 fixed top-[82px] my-8 bottom-0 p-8 text-white scrollbar scrollbar-thumb-hidden scrollbar-track-hidden">
          <>
            <div>
              <div className="md:grid md:grid-cols-3 md:gap-6">
                <div className="md:col-span-1">
                  <div className="px-4 sm:px-0">
                    <h3 className="text-lg font-medium leading-6 font-fancy">
                      Task details
                    </h3>
                    <p className="mt-1 text-sm text-gray-600">
                      This information will be displayed publicly so be careful
                      what you share.
                    </p>
                  </div>
                </div>
                <div className="mt-5 md:mt-0 md:col-span-2">
                  <form action="#" method="POST" onSubmit={onSubmitHandler}>
                    <div className="shadow sm:rounded-2xl sm:overflow-hidden">
                      <div className="px-4 py-5 bg-myColors-100 space-y-6 sm:p-6">
                        <div className="grid grid-cols-6 gap-6">
                          <div className="col-span-6 sm:col-span-6 lg:col-span-6">
                            <label
                              htmlFor="teamId"
                              className="block text-sm font-medium text-white"
                            >
                              Team Id
                            </label>
                            <input
                              type="text"
                              name="sections"
                              id="sections"
                              autoComplete="teamId"
                              onChange={onChangeHandler}
                              className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-myColors-200"
                            />
                          </div>
                          <div className="col-span-6 sm:col-span-6 lg:col-span-6">
                            <label
                              htmlFor="deadline"
                              className="block text-sm font-medium text-white"
                            >
                              Deadline
                            </label>
                            <input
                              type="text"
                              name="enddate"
                              id="enddate"
                              autoComplete="deadline"
                              onChange={onChangeHandler}
                              placeholder="31-12-2000"
                              className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-myColors-200"
                            />
                          </div>
                        </div>
                      </div>
                      <div className="px-4 py-5 bg-myColors-100 sm:p-6">
                        <div className="grid grid-cols-6 gap-6">
                          <div className="col-span-6 sm:col-span-6 lg:col-span-3">
                            <label
                              htmlFor="Id"
                              className="block text-sm font-medium text-white"
                            >
                              Id
                            </label>
                            <input
                              type="text"
                              name="Id"
                              id="Id"
                              autoComplete="Id"
                              onChange={onChangeHandler}
                              className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-myColors-200"
                            />
                          </div>

                          <div className="col-span-6 sm:col-span-3 lg:col-span-3">
                            <label
                              htmlFor="rankId"
                              className="block text-sm font-medium text-white"
                            >
                              RankId
                            </label>
                            <input
                              type="number"
                              name="RankId"
                              id="RankId"
                              autoComplete="rankId"
                              onChange={onChangeHandler}
                              className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-myColors-200"
                            />
                          </div>
                        </div>
                      </div>

                      <div className="px-4 py-5 bg-myColors-100 space-y-6 sm:p-6">
                        <div>
                          <label
                            htmlFor="about"
                            className="block text-sm font-medium text-white"
                          >
                            Summary
                          </label>
                          <div className="mt-1">
                            <textarea
                              id="Summary"
                              name="Summary"
                              onChange={onChangeHandler}
                              rows={3}
                              className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md bg-myColors-200"
                              placeholder="This task is about..."
                              defaultValue={""}
                            />
                          </div>
                          <p className="mt-2 text-sm text-gray-500">
                            Brief description for your task.
                          </p>
                        </div>
                      </div>
                      <div className="px-4 py-3 bg-myColors-300 text-right sm:px-6">
                        <button
                          type="submit"
                          className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                        >
                          Save
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </>
        </div>
      </div>
      <RightSidebar />
    </div>
  );
}

export default AssignTasks;
