import Head from "next/head";
import Image from "next/image";
import HomeContent from "../components/HomeContent";
import KanbanContent from "../components/KanbanContent";
import KanbanContent2 from "../components/KanbanContent2";
import Navbar from "../components/Navbar";
import RightSidebar from "../components/RightSidebar";
import ScheduleContent from "../components/ScheduleContent";
import Sidebar from "../components/Sidebar";
import { requirePageAuth } from "../utils/auth";
import React, { useEffect, useState } from "react";
import axios from "axios";

function Tasks({ id }) {
  const [team1, setTeam1] = useState(true);
  const [team2, setTeam2] = useState(false);

  const [team, setTeam] = useState({});
  useEffect(() => {
    getTeamByUser();
  }, []);
  const getTeamByUser = () => {
    const config = {
      method: "GET",
      url: `http://localhost:5000/sections/user/${id}`,
      // headers: {
      //   Authorization: `Bearer ${token}`,
      // },
    };
    axios(config)
      .then(({ status, data }) => {
        if (status === 200) {
          setTeam(data.data[0]);
        }
      })
      .catch((err) => {
        console.error("err", err);
      });
  };
  console.log("teamId");
  console.log(team._id);
  
  return (
    <div className="flex">
      <Head>
        <title>PFE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://cdn.syncfusion.com/ej2/20.1.55/material.css"
          rel="stylesheet"
        ></link>
      </Head>

      <Sidebar id={id} />
      <div className=" bg-myColors-100 h-screen w-7/12 relative">
        <Navbar navBarTitle_1="Tasks" navBarTitle_2={team.name} id={id} />
        {/* <ScheduleContent /> */}
    
        {team1 && <KanbanContent teamId={team._id} />}
      </div>
      <RightSidebar />
    </div>
  );
}

export const getServerSideProps = requirePageAuth;

export default Tasks;
